services:
  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - '80:80'
      - '5341:5341'
    volumes:
      - seq_data:/data

  catalog.db:
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog_db:/var/lib/postgresql/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__CatalogDbConnection=Server=catalog.db;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - RabbitMq__HostName=ecommerce-mq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - catalog.db
      - messagebroker
      - seq
    ports:
      - "5012:8080"

  notifications.db:
    container_name: notifications.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NotificationsDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_notifications_db:/var/lib/postgresql/data

  notifications.api:
    container_name: notifications.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__NotificationsDbConnection=Server=notifications.db;Port=5432;Database=NotificationsDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - notifications.db
      - seq
    ports:
      - "5013:8080"

  ordering.db:
    container_name: ordering.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=OrderingDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_ordering_db:/var/lib/postgresql/data

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__OrderingDbConnection=Server=ordering.db;Port=5432;Database=OrderingDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - ordering.db
      - messagebroker
      - seq
    ports:
      - "5014:8080"
  
  ordering.productcreatedeventconsumer:
    container_name: ordering.productcreatedeventconsumer
    environment:
      - RabbitMq__HostName=ecommerce-mq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
      - RabbitMq__QueueName=catalog.ordering.product_created_queue
      - OrderingApi__Url=http://ordering.api:8080
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - messagebroker
      - ordering.api
      - seq

  notifications.ordercreatedeventconsumer:
    container_name: notifications.ordercreatedeventconsumer
    environment:
      - RabbitMq__HostName=ecommerce-mq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
      - RabbitMq__QueueName=ordering.notifications.order_created_queue
      - NotificationsApi__Url=http://notifications.api:8080
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - messagebroker
      - notifications.api
      - seq

  catalog.ordercreatedeventconsumer:
    container_name: catalog.ordercreatedeventconsumer
    environment:
      - RabbitMq__HostName=ecommerce-mq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
      - RabbitMq__QueueName=ordering.catalog.order_created_queue
      - CatalogApi__Url=http://catalog.api:8080
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - messagebroker
      - catalog.api
      - seq
  
  ordering.stockupdatedeventconsumer:
    container_name: ordering.stockupdatedeventconsumer
    environment:
      - RabbitMq__HostName=ecommerce-mq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__VirtualHost=/
      - RabbitMq__QueueName=catalog.ordering.stock_updated_queue
      - OrderingApi__Url=http://ordering.api:8080
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    restart: always
    depends_on:
      - messagebroker
      - ordering.api
      - seq