services:
  messagebroker:
    image: rabbitmq:management
  
  seq:
    image: datalust/seq:latest
    
  catalog.db:
    image: postgres
  
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  notifications.db:
    image: postgres

  notifications.api:
    image: notifications.api
    build:
      context: .
      dockerfile: src/Services/Notifications/Notifications.API/Dockerfile
      
  ordering.db:
    image: postgres
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  ordering.productcreatedeventconsumer:
    image: ordering.productcreatedeventconsumer
    build:
      context: .
      dockerfile: src/Services/Ordering/Consumers/Ordering.ProductCreatedEventConsumer/Dockerfile

  notifications.ordercreatedeventconsumer:
    image: notifications.ordercreatedeventconsumer
    build:
      context: .
      dockerfile: src/Services/Notifications/Consumers/Notifications.OrderCreatedEventConsumer/Dockerfile

  catalog.ordercreatedeventconsumer:
    image: catalog.ordercreatedeventconsumer
    build:
      context: .
      dockerfile: src/Services/Catalog/Consumers/Catalog.OrderCreatedEventConsumer/Dockerfile

  ordering.stockupdatedeventconsumer:
    image: ordering.stockupdatedeventconsumer
    build:
      context: .
      dockerfile: src/Services/Ordering/Consumers/Ordering.StockUpdatedEventConsumer/Dockerfile

volumes:
  postgres_catalog_db:
  postgres_notifications_db:
  postgres_ordering_db:
  seq_data: